### ISSUE TITLE
making data of libFolder

### ISSUE THREAD

**Issue by Hoyeol-Jang** [rkweku/miRador#16]
Hi Author,

I don't understand while looking at the README.

libFolder --> "The name of the folder holding all of the chopped.txt files. Should not be set if libFilenamesList is used"

I didn't understand, so I checked the test/lib directory and found the GSM1402274_Col_1.S09.txt and GSM1402275_Col_2.S10.txt file.
How do I make these files?

Thank you

**Comment by rkweku** [comment]
Hello,

These are a choice that you have to define the libraries that you provide. You can set libFolder to a path containing your sequence files and miRador will use all files in the directory. If you choose this option, make sure the only files that are contained in this folders are sequence files that fit the format of miRador. However, if you wish to run on a subset of files in a single directory, or your files exist in multiple folders, you can define each library file in libFilesnamesList. Setting both options will result in an error and miRador will request that you use just one.

GSM1402274_Col_1.S09.txt and GSM1402275_Col_2.S10.txt are sample tag count files that convey the tag count format. miRador can function on fasta or fastq files though, so you do not need to create tag count files if you don't have them.

Best,
Reza
