### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by Devin561** [rkweku/miRador#6]
Dear professor,

When we run miRador, we got the problem that miRbase cannot be connected. The error information is below. How can we solve this problem?

Thank you very much!

File "./miRador-master/miRador/setupMiRBase.py", line 26, in checkNeedUpdate
    ftp = ftplib.FTP("mirbase.org")
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by rkweku** [comment]
Hi Devin,

I am actually currently awaiting a response from miRBase with regards to this issue. The FTP connection is no longer working properly and I am hoping to get a resolution from them on this soon. I'll write back as soon as I hear back.

Best,
Reza

**Comment by rkweku** [comment]
Hi there. Sorry for my delay, but after getting in touch with miRBase, I found that there was an issue with the FTP server and they had to force downloads via html. This required some modifications to the code and I've just found myself too busy lately, so I ultimately decided to store the necessary mirbase files to this repo and will remove once the ftp issue is resolved. This should now allow for runs of miRador to complete. 

Best,
Reza Hammond

**Comment by Devin561** [comment]
Hi Reza,
Thank you for your patience in helping us to solve this problem, and now we have successfully run miRador using the updated version. We believe miRador will get more people's preferred software for identifying plant miRNA.

Best Regards！
