### ISSUE TITLE
ConnectionRefusedError

### ISSUE THREAD

**Issue by Saixi-Li** [rkweku/miRador#7]
Dear professor,

Sorry to bother you, but I came across the ConnectionRefusedError when I ran miRador, beacuse of the python sentence "ftp = ftplib.FTP("mirbase.org")". And actually I find the same issue answered by you a few days ago, namely that the FTP connection is no longer working properly.

So, I get the idea that why not allow miRador to use the local data downloaded from the miRBase directly? Can this be esaily achieve so that the FTP connection would be bypassed? If possible, would you please update miRador to rejuvenate it? But of course this is just my immature suggestion.

Thank you very much!

**Comment by rkweku** [comment]
Hi there. Sorry for my delay, but after getting in touch with miRBase, I tried to implement an http workaround, but this ended up becoming too messy. I finally caved and decided to utilize your suggestion of just storing the necessary mirbase files to this repo and will remove once the ftp issue is resolved. I hope you can still find miRador useful now. 

Best,
Reza Hammond
